#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
cd "$ROOT_DIR"

cabal build all
cabal test all
bash test/scripts/run-all.sh
hlint app src test

fourmolu --config "$ROOT_DIR/fourmolu.yaml" --mode check app src test
